language: cpp
dist: trusty
os: linux

notifications:
 email:
  recipients:
  - boutwork@gmail.com
  on_success: change
  on_failure: always

git:
 depth: false

matrix:
 include:
 - os: linux
   env: "Trailing Whitespace"
   script: |
    if [[ -n $(git diff --check HEAD^) ]]; then
      echo "You must remove whitespace before submitting a pull request"
      git diff --check HEAD^
      exit -1
    fi

 - os: linux
   env: "Release/Debug/Ninja"
   addons:
    apt:
     sources: ubuntu-toolchain-r-test
     packages:
     - ninja-build
     - g++-7
   script:
   - cmake -H. -Bninja -GNinja -DCMAKE_CXX_COMPILER="g++-7"
   - cmake --build ninja

   - cmake -H. -Brelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER="g++-7"
   - cmake --build release -- -j 8
   -
   - cmake -H. -Bdebug -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER="g++-7"
   - cmake --build debug -- -j 8

 - os: linux
   env: "Test"
   addons:
    apt:
     sources: ubuntu-toolchain-r-test
     packages: g++-7
   script:
   - cmake -H. -Bbuild -DCMAKE_CXX_COMPILER="g++-7" -DCMAKE_BUILD_TYPE=Release -DENABLE_TEST=ON
   - cmake --build build -- -j 8
   - cmake --build build --target test
